/* eslint-disable @next/next/no-img-element */
"use client";
import {useEffect,useRef,useState} from "react";import {toPng} from "html-to-image";import {deleteList,getLists,saveList} from "@/lib/db";import {emptyRanking,TIERS,type List,type Tier} from "@/lib/types";
const uid=()=>crypto.randomUUID();
export function App(){const [step,setStep]=useState<"home"|"review"|"board">("home");const [topic,setTopic]=useState("");const [names,setNames]=useState<string[]>([]);const [list,setList]=useState<List|null>(null);const [recent,setRecent]=useState<List[]>([]);const [busy,setBusy]=useState(false);const board=useRef<HTMLDivElement>(null);
useEffect(()=>{getLists().then(x=>setRecent(x.sort((a,b)=>b.updatedAt-a.updatedAt)))},[]);useEffect(()=>{if(list){const t=setTimeout(()=>saveList({...list,updatedAt:Date.now()}),250);return()=>clearTimeout(t)}},[list]);
async function propose(e:React.FormEvent){e.preventDefault();setBusy(true);const r=await fetch("/api/items",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({topic})});const j=await r.json();setBusy(false);if(!r.ok)return alert(j.error);setNames(j.items);setStep("review")}
async function generate(){setBusy(true);const l:List={id:uid(),topic,items:names.filter(Boolean).slice(0,30).map(name=>({id:uid(),name,status:"loading"})),ranking:emptyRanking(),updatedAt:Date.now()};setList(l);setStep("board");const style=`bold editorial cut-paper illustration, consistent cobalt backdrop, centered subject`;for(let i=0;i<l.items.length;i+=3){await Promise.all(l.items.slice(i,i+3).map(async item=>{try{const r=await fetch("/api/image",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({topic,item:item.name,style})});const j=await r.json();setList(x=>x?{...x,items:x.items.map(v=>v.id===item.id?{...v,image:j.url,status:r.ok?undefined:"failed"}:v)}:x)}catch{setList(x=>x?{...x,items:x.items.map(v=>v.id===item.id?{...v,status:"failed"}:v)}:x)}}))}setBusy(false)}
function move(id:string,tier:Tier|"tray"){setList(x=>{if(!x)return x;const ranking={...x.ranking};for(const t of TIERS)ranking[t]=ranking[t].filter(v=>v!==id);if(tier!=="tray")ranking[tier]=[...ranking[tier],id];return{...x,ranking}})}
async function regen(id:string){if(!list)return;const item=list.items.find(x=>x.id===id)!;setList(x=>x?{...x,items:x.items.map(v=>v.id===id?{...v,status:"loading"}:v)}:x);const r=await fetch("/api/image",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({topic:list.topic,item:item.name,style:"bold editorial cut-paper illustration, cobalt backdrop"})});const j=await r.json();setList(x=>x?{...x,items:x.items.map(v=>v.id===id?{...v,image:j.url,status:r.ok?undefined:"failed"}:v)}:x)}
if(step==="home")return <main><header><b>TIERLIST<span>GEN</span></b><span>LOCAL / PRIVATE</span></header><section className="hero"><div><span className="kicker">THE DEFINITIVE RANKING MACHINE</span><h1>EVERYTHING<br/>BELONGS<br/><i>ON A TIER.</i></h1><p>Choose a topic. We’ll assemble the contenders. You settle the score.</p><form onSubmit={propose}><input required minLength={2} maxLength={100} value={topic} onChange={e=>setTopic(e.target.value)} placeholder="potato dishes" aria-label="List topic"/><button disabled={busy}>{busy?"SCOUTING…":"BUILD MY LIST →"}</button></form></div><div className="stack" aria-hidden>{TIERS.map(t=><div key={t}><b>{t}</b><span/><span/><span/></div>)}</div></section><section className="recent"><h2>RECENT LISTS</h2>{recent.length===0?<p>No debates yet. Start one above.</p>:recent.map(x=><article key={x.id}><div><b>{x.topic}</b><small>{x.items.length} contenders</small></div><button onClick={()=>{setList(x);setTopic(x.topic);setStep("board")}}>OPEN</button><button className="quiet" onClick={async()=>{await deleteList(x.id);setRecent(v=>v.filter(y=>y.id!==x.id))}}>DELETE</button></article>)}</section></main>;
if(step==="review")return <main><header><button className="link" onClick={()=>setStep("home")}>← BACK</button><b>TIERLIST<span>GEN</span></b></header><section className="review"><span className="kicker">CONTENDER CHECK</span><h1>WHO MAKES<br/><i>THE CUT?</i></h1><p>Rename, remove, add, or drag with the handles to reorder. Confirm before images are generated.</p><div>{names.map((n,i)=><div className="edit" key={i}><button aria-label="Move up" disabled={!i} onClick={()=>setNames(v=>{const x=[...v];[x[i-1],x[i]]=[x[i],x[i-1]];return x})}>↟</button><input value={n} onChange={e=>setNames(v=>v.map((x,j)=>j===i?e.target.value:x))}/><button aria-label="Remove" onClick={()=>setNames(v=>v.filter((_,j)=>j!==i))}>×</button></div>)}</div><button className="outline" onClick={()=>names.length<30&&setNames(v=>[...v,"New contender"])}>+ ADD CONTENDER</button><button className="confirm" disabled={busy||!names.some(Boolean)} onClick={generate}>CONFIRM & GENERATE IMAGES →</button></section></main>;
if(!list)return null;const ranked=new Set(TIERS.flatMap(t=>list.ranking[t]));const card=(id:string)=>{const x=list.items.find(i=>i.id===id)!;return <div className="card" key={id} draggable onDragStart={e=>e.dataTransfer.setData("id",id)}><div className="pic">{x.image?<img src={x.image} alt=""/>:<span>{x.status==="failed"?"!":"…"}</span>}</div><b>{x.name}</b><select aria-label={`Move ${x.name}`} value={ranked.has(id)?TIERS.find(t=>list.ranking[t].includes(id)):"tray"} onChange={e=>move(id,e.target.value as Tier|"tray")}><option value="tray">Unranked</option>{TIERS.map(t=><option key={t}>{t}</option>)}</select><button className="regen" onClick={()=>regen(id)}>↻</button></div>};
return <main><header><button className="link" onClick={()=>setStep("home")}>← LISTS</button><b>TIERLIST<span>GEN</span></b><button onClick={async()=>{if(board.current){const url=await toPng(board.current,{backgroundColor:"#111"});const a=document.createElement("a");a.href=url;a.download=`${list.topic}-tier-list.png`;a.click()}}}>EXPORT PNG</button></header><section className="board-head"><span className="kicker">RANKING IN PROGRESS</span><h1>{list.topic}</h1><p>{ranked.size} of {list.items.length} ranked {busy?"· images generating…":""}</p></section><div className="board" ref={board}>{TIERS.map(t=><div className={`tier tier-${t}`} key={t} onDragOver={e=>e.preventDefault()} onDrop={e=>move(e.dataTransfer.getData("id"),t)}><div className="tier-label">{t}</div><div className="tier-cards">{list.ranking[t].map(card)}</div></div>)}</div><section className="tray" onDragOver={e=>e.preventDefault()} onDrop={e=>move(e.dataTransfer.getData("id"),"tray")}><h2>UNRANKED <span>{list.items.length-ranked.size}</span></h2><div>{list.items.filter(x=>!ranked.has(x.id)).map(x=>card(x.id))}</div></section></main>}
